### ISSUE TITLE
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

### ISSUE THREAD

**Issue by kirillin** [NickoDema/kobuki#1]
Hello!

Now I get some task and I needed to use nvidia drivers. I used your docker installation script, but it didn't work for me.

Seems, that for nvidia graphics within docker need to install aslo `nvidia-container-runtime`.

May be add it here

https://github.com/NickoDema/kobuki/blob/a1448cd2e70ad98c62cb060940a36aad6507bdf5/scripts/docker_install.bash#L30

Thanks for your time and let the force be with you!

**Comment by NickoDema** [comment]
> Seems, that for nvidia graphics within docker need to install aslo `nvidia-container-runtime`.

Hi, starting from docker 19.03 there is no need to use the nvidia-container-runtime. Check this link : https://unrealcontainers.com/docs/concepts/nvidia-docker
